### ISSUE TITLE
TypeError: Cannot read property 'now' of undefined in 1.1.0

### ISSUE THREAD

**Issue by chetmurphy** [TheBrainFamily/wait-for-expect#17]
I am using typescript with react-hooks-testing-library that uses this library. To get tests to run, I had to mock Date in my tests

declare global {
  interface Window { Date: any; }
}
window.Date = Date;

And comment out the code in wait-for-expect starting at line 16:

var _ref = typeof window !== "undefined" ? window : global,
   setTimeout = _ref.setTimeout,
   now = _ref.Date.now;

Is this a bug?

**Comment by lgandecki** [comment]
Moving the discussion from #12 
Repro at https://github.com/chetmurphy/wait-for-expect-test - you do some weird things there, the whole setup of enzyme is not needed when you use *-testing-library.
To sum up, I removed setupFiles and testEnvironment from your package.json and it worked. 

![Screen Shot 2019-03-25 at 12 57 48 PM](https://user-images.githubusercontent.com/4002543/54907020-04c21a00-4efe-11e9-8001-fb25daf40792.png)
![Screen Shot 2019-03-25 at 12 57 44 PM](https://user-images.githubusercontent.com/4002543/54907025-07247400-4efe-11e9-85b4-496bd10b07ec.png)


I don't think this is a bug in the library, when you start mocking your globals, windows, etc, things might start breaking. 

Also, your mocking of date in Block.test.tsx could not work - since the code is breaking on the import, before you even get to your "mock"

**Comment by chetmurphy** [comment]
Confirmed and thanks.

________________________________

**Comment by eric-burel** [comment]
Hi, for lost googlers that struggled like me, I needed to initialize JSDOM this way server side so `window` object is fully defined: 

```
import jsdom from "jsdom-global";

const initComponentTest = () => {
	// init jsdom for SSR
	jsdom("", {
		runScripts: "outside-only"
	});
```
For the details this manual initialization of JSDOM is needed to test components with Enzyme server side in Vulcan (a Meteor + Mocha + React setup with SSR).

The `runScripts` option will load `window.Date`, `window.Map` and so on, that are not included in JSDOM as a default [as stated in their doc](https://github.com/jsdom/jsdom#executing-scripts).

As explained in #15 maybe it would nice to catch this error early on in `wait-for-expect`, because it's quite hard to debug and can easily happen with a bad setup/too much mocking.
